language: node_js
node_js:
- "node"
notifications:
  email: false
deploy:
  provider: heroku
  api_key: ThtbT41kKalLawOuW7O1WTnJyxly5iRpWj8gW+Fo9PQU330U8IAC6iSk0r4/OvTyPwuB8GurhFArHOxfBCgSXU6yuCP4LsHnOa645sKbFeN5gTi7UQLWbVcDsrGCMO/UTdV7wJjn/MnkjivWii+R1Yuw/ejvBZDrZvteTxHjd+cgdgGjvirMvm/1GdEBsZ+WZxugQqQUjlKwgfRjNFS9h8o1Wotqeyc4XcnsQ1hgY0pdPcBWMyjAW1beoK7Dp7RS1ayMRYBKWQnmyTEoOQMC1smhxiJUN4AMdWbmeZIKxtcWrDa0tMrQ0DFKQrGHjYfE0iIOZbg3/wAoS3Dw154v6k0RpKZhwQ1Pt2jTF5WlbjbOuiR0oyT7Rh9i9Pg9P55/BZId/IsxginVit3/IuTgxZWO7RCt4e2B6SYuIrm3ncA+9XXlJivGWo3fUShO28bJUqT1dokVitk/bPYhO26Riw6qj6BMgiAwk8izj/HOuUBIOZulF9WmvxEOHQMdx4krJPLPiIwmGMQ9fotexbn32L2x0fc25L21dyMyEN9c6R1IMU/prU/iY3SAqCCnbdWq24IfP8rzvsb2SsI+lqYKjt+mscGob2EClkRz3aIITiOcaCDpAV3rk/3KqWQW7Wz1FvmZHyOhOEMNG43eQh0yXcpj5X2EhFtvEYxNUoeGb/E=
  app: the-random-gender-ator
  skip_cleanup: true
  on:
    branch: main
