language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key: JP0Ygy9V4PIMCZbcrfXrDqWIKW9sGJM3mZ+S12wOBgeuguv8NgYDdBFGDQ9h0D5Zz496G6zJjH9EiysdnnyudYgSa43CbRhWTmPVypihSryx+YT/12vlPVqi+7ZyKXlec0IN3e+pJJZ0KstARw7KVlgrFxbAkz5ydLFIX1HWIxcyWk/SoebjKXm0deV9LfeztyOSlJ/1ea4odSp6WF9xaRoVnIi7DdzLb0IZSqNkUl549DuRPy5zSWEmQa26KXAi3uAVE/NRal8RXb8pyTWJgrueTbxLo5OTqnBS9OWxt16pA7I4fnpUp3TnoKarz7FmvxyTw4qswX26T9mPW3wmXRQnkKP0oPDmNIGQ8kFBCMHuphupkIfDHmPCU7moqwktyYsoLlr6yI0eg0tBnGTHfx54TQNGGwMACMuF3o4B0CA1Mivjzj8Dj4sFnBg51BAxCYzP1MEB1+pdxm8PX4hF1apGlWBK/CxXqMPzQ9EW1G5UxmBl+srtNe/nCnlhb7DSZ33B5TAw6Vyi0TrR6u+C428+uQPbeO9eBcVwNAtRD2RN4T5AdXZQYc1m6ggol258MoQZ7fXRUSkgxaubgayDoB+hcyk59vmxretjw3bpylKa6D5U2UtMDWqdpznQoXE6idZ2tFXenuGxxf5Tb2o8VRaTEePMwNh6safbFmaRiXc=
  app: the-random-gender-ator
  skip_cleanup: true
